#!/usr/bin/env python3
"""
Comprehensive test to verify Level 3 service handling in vendor application flow
Tests the full workflow from form submission to service matching
"""

import json
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def simulate_vendor_form_submission():
    """Simulate a vendor form submission with Level 3 services"""
    
    # Simulate vendor application payload with Level 3 services
    vendor_payload = {
        "firstName": "Joe",
        "lastName": "Fisher",
        "email": "test+joe@ezwai.com",
        "phone": "(555) 123-4567",
        "vendor_company_name": "Joe's Premium Fishing Charters",
        
        # Level 1 - Primary Category
        "primary_service_category": "Charters and Tours",
        
        # Level 2 - Subcategories selected
        "primary_services": ["Fishing Charters"],
        
        # Level 3 - Specific services (vendor deselected some)
        "primary_level3_services": {
            "Fishing Charters": [
                "Inshore Fishing Charter",
                "Offshore (Deep Sea) Fishing Charter",
                "Reef & Wreck Fishing Charter",
                # NOT including:
                # "Drift Boat Charter",
                # "Freshwater Fishing Charter",
                # "Private Party Boat Charter"
            ]
        },
        
        # Additional services
        "additional_categories": [],
        "additional_services": [],
        "additional_level3_services": {},
        
        # Coverage
        "coverage_type": "county",
        "coverage_counties": ["Miami-Dade County, FL", "Broward County, FL"],
        
        # Combined field (will be generated by webhook handler)
        "services_provided": ""  # This should be populated with Level 3 services
    }
    
    print("\n" + "="*60)
    print("SIMULATED VENDOR FORM SUBMISSION")
    print("="*60)
    print(f"Vendor: {vendor_payload['vendor_company_name']}")
    print(f"Email: {vendor_payload['email']}")
    print(f"Primary Category: {vendor_payload['primary_service_category']}")
    print(f"Primary Services (Level 2): {vendor_payload['primary_services']}")
    print(f"Level 3 Services Selected:")
    for subcategory, services in vendor_payload['primary_level3_services'].items():
        print(f"  {subcategory}:")
        for service in services:
            print(f"    ✅ {service}")
    print("\nServices NOT selected (vendor doesn't offer):")
    print("    ❌ Drift Boat Charter")
    print("    ❌ Freshwater Fishing Charter")
    print("    ❌ Private Party Boat Charter")
    
    return vendor_payload

def test_service_extraction(vendor_payload):
    """Test how services are extracted from the form data"""
    
    print("\n" + "="*60)
    print("TESTING SERVICE EXTRACTION LOGIC")
    print("="*60)
    
    # Simulate the webhook handler's service extraction logic
    primary_level3_services = vendor_payload.get('primary_level3_services', {})
    additional_level3_services = vendor_payload.get('additional_level3_services', {})
    
    services_list = []
    
    # Collect all Level 3 services
    if primary_level3_services and isinstance(primary_level3_services, dict):
        for subcategory, level3_list in primary_level3_services.items():
            if isinstance(level3_list, list):
                services_list.extend(level3_list)
                print(f"📋 Extracted Level 3 services for {subcategory}: {level3_list}")
    
    if additional_level3_services and isinstance(additional_level3_services, dict):
        for subcategory, level3_list in additional_level3_services.items():
            if isinstance(level3_list, list):
                services_list.extend(level3_list)
    
    # If no Level 3 services, fall back to Level 2
    if not services_list:
        print("⚠️ No Level 3 services found, falling back to Level 2")
        services_list = vendor_payload.get('primary_services', [])
    
    print(f"\n✅ Final services_offered for vendor: {services_list}")
    return services_list

def test_lead_matching(services_offered):
    """Test how leads would be matched to this vendor"""
    
    print("\n" + "="*60)
    print("TESTING LEAD MATCHING")
    print("="*60)
    
    from api.services.lead_routing_service import LeadRoutingService
    routing_service = LeadRoutingService()
    
    # Create a mock vendor with the extracted services
    vendor = {
        'name': "Joe's Premium Fishing Charters",
        'services_offered': services_offered
    }
    
    # Test various lead scenarios
    test_scenarios = [
        {
            'lead_service': 'Inshore Fishing Charter',
            'expected': True,
            'reason': 'Vendor offers this specific Level 3 service'
        },
        {
            'lead_service': 'Offshore (Deep Sea) Fishing Charter',
            'expected': True,
            'reason': 'Vendor offers this specific Level 3 service'
        },
        {
            'lead_service': 'Freshwater Fishing Charter',
            'expected': False,
            'reason': 'Vendor deselected this Level 3 service'
        },
        {
            'lead_service': 'Drift Boat Charter',
            'expected': False,
            'reason': 'Vendor deselected this Level 3 service'
        },
        {
            'lead_service': 'Fishing Charters',
            'expected': False,
            'reason': 'Vendor has Level 3 services, should not match Level 2 category'
        },
        {
            'lead_service': 'Fishing Charter',
            'expected': False,
            'reason': 'Generic term should not match when vendor has specific services'
        }
    ]
    
    print("\nLead Matching Results:")
    print("-" * 60)
    
    all_passed = True
    for scenario in test_scenarios:
        result = routing_service._vendor_matches_service(vendor, scenario['lead_service'])
        expected = scenario['expected']
        passed = result == expected
        
        if not passed:
            all_passed = False
        
        status = "✅ PASS" if passed else "❌ FAIL"
        match_status = "MATCH" if result else "NO MATCH"
        
        print(f"\nLead requests: '{scenario['lead_service']}'")
        print(f"  Expected: {'MATCH' if expected else 'NO MATCH'}")
        print(f"  Got: {match_status}")
        print(f"  Status: {status}")
        print(f"  Reason: {scenario['reason']}")
    
    return all_passed

def main():
    """Run the comprehensive test"""
    
    print("\n" + "="*70)
    print("COMPREHENSIVE LEVEL 3 SERVICE HANDLING TEST")
    print("="*70)
    
    # Step 1: Simulate vendor form submission
    vendor_payload = simulate_vendor_form_submission()
    
    # Step 2: Test service extraction
    services_offered = test_service_extraction(vendor_payload)
    
    # Step 3: Test lead matching
    all_tests_passed = test_lead_matching(services_offered)
    
    # Summary
    print("\n" + "="*60)
    print("TEST SUMMARY")
    print("="*60)
    
    if all_tests_passed:
        print("✅ ALL TESTS PASSED!")
        print("\nThe system correctly:")
        print("1. Extracts Level 3 services from vendor applications")
        print("2. Stores them as services_offered in the database")
        print("3. Matches leads ONLY to the specific Level 3 services selected")
        print("4. Prevents vendors from getting leads for services they deselected")
    else:
        print("❌ SOME TESTS FAILED")
        print("\nPlease review the failed tests above")
    
    print("\n" + "="*60)
    print("Key Implementation Points:")
    print("="*60)
    print("1. Vendor forms send primary_level3_services and additional_level3_services")
    print("2. Webhook handler extracts Level 3 services when available")
    print("3. Lead routing checks if vendor has Level 3 services")
    print("4. If vendor has Level 3, they ONLY match exact Level 3 services")
    print("5. This prevents misrouted leads (e.g., bass fishing to saltwater charter)")

if __name__ == "__main__":
    main()